---
# tasks file for ansible-role-pkg

- name: Raise exception if ansible_os_family is not FreeBSD
  fail:
    msg: "Platform {{ ansible_os_family }} is not supported"
  when:
    - ansible_os_family != 'FreeBSD'

- include_vars: "{{ ansible_os_family }}.yml"

# XXX create configuration files before install tasks
- name: Create pkg.conf
  template:
    src: pkg.conf.j2
    dest: "{{ pkg_conf }}"

- name: Create repo dir
  file:
    path: "{{ pkg_repos_dir }}"
    state: directory
    mode: 0755

- name: Create repository conf
  template:
    src: site.conf.j2
    dest: "{{ pkg_repos_dir }}/{{ item.key }}.conf"
    mode: 0644
  with_dict: "{{ pkg_repos }}"

- include: install-FreeBSD.yml
